services:
  db:
    image: postgres
    networks:
      my_network:
        ipv4_address: 172.28.0.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      my_network:
        ipv4_address: 172.28.0.2
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID} 
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
