import { IconCompass, IconDownload, IconGlobe, IconMap, IconTicket, IconTimeline } from '@tabler/icons-react';
import {
  BellIcon,
  CalendarIcon,
  FileTextIcon,
  GlobeIcon,
  InputIcon,
} from "@radix-ui/react-icons";

export const features = [
  {
    Icon: FileTextIcon as React.ElementType,
    name: "Save your files",
    description: "We automatically save your files as you type.",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-1 lg:row-end-3 lg:col-start-1 lg:col-end-2",
  },
  {
    Icon: InputIcon as React.ElementType,
    name: "Full text search",
    description: "Search through all your files in one place.",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-1 lg:row-end-2 lg:col-start-2 lg:col-end-3",
  },
  {
    Icon: GlobeIcon as React.ElementType,
    name: "Multilingual",
    description: "Supports 100+ languages and counting.",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-2 lg:row-end-3 lg:col-start-2 lg:col-end-3",
  },
  {
    Icon: CalendarIcon as React.ElementType,
    name: "Calendar",
    description: "Use the calendar to filter your files by date.",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-1 lg:row-end-2 lg:col-start-3 lg:col-end-4",
  },
  {
    Icon: BellIcon as React.ElementType,
    name: "Notifications",
    description:
      "Get notified when someone shares a file or mentions you in a comment.",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-2 lg:row-end-3 lg:col-start-3 lg:col-end-4",
  },
  {
    Icon: IconGlobe as React.ElementType,
    name: "A customized journey",
    description: "Find destinations for your next trip",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-3 lg:row-end-4 lg:col-start-1 lg:col-end-3",
  },
  {
    Icon: IconMap as React.ElementType,
    name: "Plan your itinerary",
    description: "Create your itinerary from start to finish",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-3 lg:row-end-5 lg:col-start-3 lg:col-end-4",
  },
  {
    Icon: IconCompass as React.ElementType,
    name: "Activity suggestions",
    description: "Receive activity suggestions based on your preferences",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-4 lg:row-end-5 lg:col-start-1 lg:col-end-2",
  },
  {
    Icon: IconTimeline as React.ElementType,
    name: "Time estimate calculation",
    description: "Calculate the estimated time for each activity",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-4 lg:row-end-5 lg:col-start-2 lg:col-end-3",
  },
  {
    Icon: IconTicket as React.ElementType,
    name: "Book your tickets",
    description: "Book your flight, train, or bus tickets",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-5 lg:row-end-6 lg:col-start-1 lg:col-end-3",
  },
  {
    Icon: IconDownload as React.ElementType,
    name: "Download your itinerary",
    description: "Download your itinerary for offline use",
    href: "/",
    cta: "Learn more",
    className: "lg:row-start-5 lg:row-end-6 lg:col-start-3 lg:col-end-4",
  },
];
